### ISSUE TITLE
Converting ioll2 images

### ISSUE THREAD

**Issue by fatman00** [CiscoDevNet/eve2cml#9]
I have tried to figure out why some of the .unl files I have with L2 switches does not get converted to the right type by eve2cml. And i cannot figure out why.

I have a L2 IOL node with the following definition:
```
      <node id="9" name="SW1" type="iol" template="iol" image="i86bi_linux_l2-advipservicesk9-ms.high_iron_20170202.bin" ethernet="7" nvram="1024" ram="1024" serial="0" delay="0" sat="-1" icon="Switch L3.png" config="1" left="213" top="432">
        <interface id="16" name="e0/1" type="ethernet" network_id="22" labelpos="0.5" curviness="10" beziercurviness="150" midpoint="0.5" srcpos="0.15" dstpos="0.85"/>
        <interface id="1" name="e1/0" type="ethernet" network_id="32" labelpos="0.5" curviness="10" beziercurviness="150" midpoint="0.5" srcpos="0.15" dstpos="0.85"/>
```
This node is being converted to **iol-xe**, but will only work if it is converted to **ioll2-xe**. I have looked at the built-in mapper, and as far as I understand it should match and convert it to **ioll2-xe**.

```
map:
  iol:iol:i86bi_linux_l2:
    image_def: null
    node_def: ioll2-xe
    override: false
```
But it does not work and the resulting CML YAML file includes the following node_definition:

```
  cpu_limit: null
  cpus: null
  data_volume: null
  hide_links: false
  label: SW1
  node_definition: iol-xe
  image_definition: null
```
Any hints on how to solve this using a custom mapper would be great.

**Comment by rschmied** [comment]
@fatman00  -- sorry, I only saw this now. Would you be able to provide the .unl ?

**Comment by fatman00** [comment]
@rschmied I just made a small test file with a single IOL-L2 switch.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<lab name="converter" version="1" scripttimeout="300" countdown="0" linkwidth="2" lock="0" grid="1" sat="-1">
  <topology>
    <nodes>
      <node id="1" name="SW01" type="iol" template="iol" image="i86bi_linux_l2-advipservicesk9-ms.high_iron_20170202.bin" ethernet="1" nvram="1024" ram="1024" serial="0" keepalive="0" delay="0" sat="-1" icon="Router-2D-Gen-White-S.svg" config="0" left="594" top="210"/>
    </nodes>
  </topology>
</lab>
```

And the resulting yaml file is:
```
lab:
  notes: Imported from convert.unl via `eve2cml` converter
  description: Imported from convert.unl via eve2cml converter
  title: converter
  version: 0.1.0
annotations: []
links: []
nodes:
- id: n1
  boot_disk_size: null
  configuration: ''
  cpu_limit: null
  cpus: null
  data_volume: null
  hide_links: false
  label: SW01
  node_definition: iol-xe
  image_definition: null
  ram: 1024
  tags: []
  x: 594
  y: 210
  interfaces:
  - id: i0
    label: Ethernet0/0
    slot: 0
    type: physical
```
Let me know if you need anything more.

**Comment by fatman00** [comment]
This is another example of the same but with another image, where the image name includes capital letters:

convert.unl:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<lab name="converter" version="1" scripttimeout="300" countdown="0" linkwidth="2" lock="0" grid="1" sat="-1">
  <topology>
    <nodes>
      <node id="1" name="SW01" type="iol" template="iol" image="i86bi_Linux-L2-AdvEnterpriseK9-M_152_May_2018.bin" ethernet="1" nvram="1024" ram="1024" serial="0" keepalive="0" delay="0" sat="-1" icon="Router-2D-Gen-White-S.svg" config="0" left="594" top="210"/>
    </nodes>
  </topology>
</lab>
```
convert.yml:

```
lab:
  notes: Imported from convert.unl via `eve2cml` converter
  description: Imported from convert.unl via eve2cml converter
  title: converter
  version: 0.1.0
annotations: []
links: []
nodes:
- id: n1
  boot_disk_size: null
  configuration: ''
  cpu_limit: null
  cpus: null
  data_volume: null
  hide_links: false
  label: SW01
  node_definition: iol-xe
  image_definition: null
  ram: 1024
  tags: []
  x: 594
  y: 210
  interfaces:
  - id: i0
    label: Ethernet0/0
    slot: 0
    type: physical
```
